# Generated by Django 4.1.5 on 2023-05-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_kamars_nomor_kamar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengelolas',
            name='nik',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pengelolas',
            name='alamat',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pengelolas',
            name='nama',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pengelolas',
            name='no_telepon',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pengelolas',
            name='tanggal_lahir',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
