# Generated by Django 4.1.5 on 2023-05-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pengelolas_nik_alter_pengelolas_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengelolas',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
