# Generated by Django 4.1.5 on 2023-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pengelolas_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengelolas',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-laki', 'laki-laki'), ('Perempuan', 'perempuan')], default=None, max_length=20, null=True),
        ),
    ]
